---
title: "Open Redcedar Active Analyses Page"
author:  "Contributors: Joey Hulbert,... "
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
---

|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[Redcedar](https://jmhulbert.github.io/open/redcedar)|[Data](https://jmhulbert.github.io/open/redcedar/data)|[ Analyses](https://jmhulbert.github.io/open/redcedar/analyses)|[Instructions](https://jmhulbert.github.io/open/redcedar/instructions)|
|             |           |            |            |


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Active Analyses

Below is a list of active analyses and contributors. Each analysis has a page describing the methods of analysis

* Analyses
  + Random forests Analyses
    + [climate data](https://jmhulbert.github.io/open/redcedar/analyses/random-forests/climate)
    + soils data
      + [xPolaris data](https://jmhulbert.github.io/open/redcedar/analyses/random-forests/soils/xpolaris)
      + [gssurgo data - Brendan Farrell](https://jmhulbert.github.io/open/redcedar/analyses/random-forests/soils/gssurgo)
    + [topo data](https://jmhulbert.github.io/open/redcedar/analyses/random-forests/topo/)
    + [combined data](https://jmhulbert.github.io/open/redcedar/analyses/random-forests/combined/)
  + Spatial Analyses
    + Spatial autocorrelation
    + Distribution overlays with historic and predicted maps (eg Crookston et al 2009)
      + Maps of where the healthy trees are and where the unhealthy trees are 
      + Areas where they agree - focus restoration
      + Areas where they disagree - monitor redcedar to see where they go
    + Cluster analysis
    + Rural vs urban
  + Hypothesis tests
    + [Distance from waterways - Rubén Rodriguez](./distance-to-waterways/)
    + Soil Depth
  + Explore one of the above or add your jam here..

## To-Do list
  + extract topo data
  + random forests with topo data
  + explore utility of Brendan's ggsurgo dataset
  + random forests with combined datasets
  + explore other random forests flavors (ranger and probabilistic forests rather than rf right out of the box)
  + map distribution of the 600 trees with water table depth data 

